version: "3"

services:
  node:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    volumes:
      - ./config:/usr/app/config
    environment:
      - NODE_ENV=development
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    depends_on:
      - node
    ports:
      - 3000:3000
